from .wordcount import count_specific_word
from .mostcommonword import identify_most_common_word
from .avgwordlength import calculate_average_word_length
from .countparagraphs import count_paragraphs
from .countsentences import count_sentences